[package]
name = "nn-cuda"
version = "0.1.0"
edition = "2024"
description = "CUDA kernels for MoE Transformer"
license = "MIT"
build = "build.rs"

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
