name = "MoETransformer"
uuid = "f225dc8c-907a-4468-a86b-d18a973532d6"
version = "0.1.0"
license = "CC-BY-4.0"

[deps]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AppleAccelerate = "0.5"
julia = "1.10"
